from aiogram.fsm.state import State, StatesGroup


class States(StatesGroup):
    MAIN_MENU = State()
    REGISTRATION = State()
    EDIT_ADMIN_LIST = State()
    TAKE_THE_SURVEY = State()
    ADD_USER_TO_ADMIN_LIST = State()
    DELETE_USER_FROM_ADMIN_LIST = State()
    ENTER_NEW_ADMIN = State()
    EDIT_SURVEYS = State()
    ADD_SURVEY = State()
    ENTER_SURVEY_VALUE = State()
    EDIT_SURVEY = State()
    CHANGE_SURVEY = State()
    EDIT_SURVEY_STEP = State()
    CHANGE_SURVEY_STEP = State()
    ADD_STEP = State()
    SET_STEPS_ORDER = State()
    ENTER_SURVEY_STEP_NEW_VALUE = State()
    ENTER_SURVEY_NEW_VALUE = State()
    ENTER_NEW_STEPS_ORDER = State()
    ENTER_SURVEY_STEP_VALUE = State()
    SELECT_TAKE_SURVEY = State()
    PROCESSED_SURVEY = State()
    SEND_MESSAGE_TO_ADMIN = State()
